/* The following code was generated by JFlex 1.4.3 on 03/12/25, 21:39 */

package codigo;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 03/12/25, 21:39 from the specification file
 * <tt>C:/Users/alanc/OneDrive/Documents/Tec/11vo Semestre/Lenguajes y Automatas 1/Unidad 4/Proyecto Compilador/compilercode-compilador/src/codigo/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\60\1\6\2\0\1\60\22\0\1\60\1\43\1\4\1\61"+
    "\2\0\1\45\1\0\1\51\1\52\1\42\1\42\1\55\1\42\1\0"+
    "\1\42\12\3\1\56\1\57\1\44\1\40\1\41\2\0\17\2\1\37"+
    "\2\2\1\36\1\35\6\2\1\53\1\5\1\54\1\0\1\1\1\0"+
    "\1\15\1\31\1\7\1\30\1\20\1\24\1\25\1\34\1\13\1\33"+
    "\1\26\1\14\1\11\1\21\1\10\1\12\1\2\1\16\1\17\1\23"+
    "\1\32\1\27\1\2\1\22\2\2\1\47\1\46\1\50\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\0\1\3\20\1\1\4\1\5"+
    "\1\6\1\7\2\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\0\15\1"+
    "\1\23\17\1\1\5\1\24\1\7\50\1\1\25\14\1"+
    "\1\26\25\1\1\27\11\1\1\30\1\31\1\1\1\32"+
    "\6\1\1\33\1\34\5\1\1\35\13\1\1\36\2\1"+
    "\1\37\11\1\1\40\4\1\1\41\6\1\1\42\7\1"+
    "\1\43\2\1\1\44\1\1\1\45\1\1\1\46\11\1"+
    "\1\47\1\1\1\50\1\1\1\51\1\1\1\52\2\1"+
    "\1\53\22\1\1\54\37\1\1\55\26\1\1\56\15\1"+
    "\1\57\2\1\1\60\1\61\16\1\1\62\6\1\1\63"+
    "\4\1\1\64\3\1\1\65\3\1\1\66\1\67\1\1"+
    "\1\70\1\71\1\1\1\72\7\1\1\73\3\1\1\74"+
    "\2\1\1\75\1\1\1\76\3\1\1\77\1\100\2\1"+
    "\1\101";

  private static int [] zzUnpackAction() {
    int [] result = new int[403];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee"+
    "\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c\0\u047e"+
    "\0\u044c\0\u04b0\0\u04e2\0\u047e\0\u047e\0\u047e\0\u047e\0\u047e"+
    "\0\u047e\0\u047e\0\u047e\0\u047e\0\u0514\0\u047e\0\u0546\0\u0578"+
    "\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708"+
    "\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898"+
    "\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992\0\u09c4\0\u09f6\0\u0a28"+
    "\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u047e\0\u047e\0\u047e\0\u0b22"+
    "\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2"+
    "\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\u0e42"+
    "\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2"+
    "\0\u1004\0\u1036\0\u1068\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162"+
    "\0\u1194\0\u11c6\0\u11f8\0\u122a\0\u125c\0\u128e\0\u12c0\0\62"+
    "\0\u12f2\0\u1324\0\u1356\0\u1388\0\u13ba\0\u13ec\0\u141e\0\u1450"+
    "\0\u1482\0\u14b4\0\u14e6\0\u1518\0\62\0\u154a\0\u157c\0\u15ae"+
    "\0\u15e0\0\u1612\0\u1644\0\u1676\0\u16a8\0\u16da\0\u170c\0\u173e"+
    "\0\u1770\0\u17a2\0\u17d4\0\u1806\0\u1838\0\u186a\0\u189c\0\u18ce"+
    "\0\u1900\0\u1932\0\62\0\u1964\0\u1996\0\u19c8\0\u19fa\0\u1a2c"+
    "\0\u1a5e\0\u1a90\0\u1ac2\0\u1af4\0\62\0\62\0\u1b26\0\62"+
    "\0\u1b58\0\u1b8a\0\u1bbc\0\u1bee\0\u1c20\0\u1c52\0\u1c84\0\u1cb6"+
    "\0\u1ce8\0\u1d1a\0\u1d4c\0\u1d7e\0\u1db0\0\62\0\u1de2\0\u1e14"+
    "\0\u1e46\0\u1e78\0\u1eaa\0\u1edc\0\u1f0e\0\u1f40\0\u1f72\0\u1fa4"+
    "\0\u1fd6\0\62\0\u2008\0\u203a\0\62\0\u206c\0\u209e\0\u20d0"+
    "\0\u2102\0\u2134\0\u2166\0\u2198\0\u21ca\0\u21fc\0\62\0\u222e"+
    "\0\u2260\0\u2292\0\u22c4\0\62\0\u22f6\0\u2328\0\u235a\0\u238c"+
    "\0\u23be\0\u23f0\0\62\0\u2422\0\u2454\0\u2486\0\u24b8\0\u24ea"+
    "\0\u251c\0\u254e\0\62\0\u2580\0\u25b2\0\62\0\u25e4\0\u2616"+
    "\0\u2648\0\62\0\u267a\0\u26ac\0\u26de\0\u2710\0\u2742\0\u2774"+
    "\0\u27a6\0\u27d8\0\u280a\0\62\0\u283c\0\62\0\u286e\0\62"+
    "\0\u28a0\0\62\0\u28d2\0\u2904\0\62\0\u2936\0\u2968\0\u299a"+
    "\0\u29cc\0\u29fe\0\u2a30\0\u2a62\0\u2a94\0\u2ac6\0\u2af8\0\u2b2a"+
    "\0\u2b5c\0\u2b8e\0\u2bc0\0\u2bf2\0\u2c24\0\u2c56\0\u2c88\0\62"+
    "\0\u2cba\0\u2cec\0\u2d1e\0\u2d50\0\u2d82\0\u2db4\0\u2de6\0\u2e18"+
    "\0\u2e4a\0\u2e7c\0\u2eae\0\u2ee0\0\u2f12\0\u2f44\0\u2f76\0\u2fa8"+
    "\0\u2fda\0\u300c\0\u303e\0\u3070\0\u30a2\0\u30d4\0\u3106\0\u3138"+
    "\0\u316a\0\u319c\0\u31ce\0\u3200\0\u3232\0\u3264\0\u3296\0\62"+
    "\0\u32c8\0\u32fa\0\u332c\0\u335e\0\u3390\0\u33c2\0\u33f4\0\u3426"+
    "\0\u3458\0\u348a\0\u34bc\0\u34ee\0\u3520\0\u3552\0\u3584\0\u35b6"+
    "\0\u35e8\0\u361a\0\u364c\0\u367e\0\u36b0\0\u36e2\0\62\0\u3714"+
    "\0\u3746\0\u3778\0\u37aa\0\u37dc\0\u380e\0\u3840\0\u3872\0\u38a4"+
    "\0\u38d6\0\u3908\0\u393a\0\u396c\0\62\0\u399e\0\u39d0\0\62"+
    "\0\62\0\u3a02\0\u3a34\0\u3a66\0\u3a98\0\u3aca\0\u3afc\0\u3b2e"+
    "\0\u3b60\0\u3b92\0\u3bc4\0\u3bf6\0\u3c28\0\u3c5a\0\u3c8c\0\62"+
    "\0\u3cbe\0\u3cf0\0\u3d22\0\u3d54\0\u3d86\0\u3db8\0\62\0\u3dea"+
    "\0\u3e1c\0\u3e4e\0\u3e80\0\62\0\u3eb2\0\u3ee4\0\u3f16\0\62"+
    "\0\u3f48\0\u3f7a\0\u3fac\0\62\0\62\0\u3fde\0\62\0\62"+
    "\0\u4010\0\62\0\u4042\0\u4074\0\u40a6\0\u40d8\0\u410a\0\u413c"+
    "\0\u416e\0\62\0\u41a0\0\u41d2\0\u4204\0\62\0\u4236\0\u4268"+
    "\0\62\0\u429a\0\62\0\u42cc\0\u42fe\0\u4330\0\62\0\62"+
    "\0\u4362\0\u4394\0\62";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[403];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\2\1\3\1\4\1\0\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\2\1\21\1\22\1\23\1\2\1\24\1\25"+
    "\7\2\1\26\1\27\1\30\1\31\1\27\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\5\1\45\1\0\3\2\3\0\31\2\25\0"+
    "\1\3\56\0\4\4\1\46\1\47\54\4\6\0\1\5"+
    "\51\0\1\5\2\0\3\2\3\0\1\2\1\50\4\2"+
    "\1\51\22\2\23\0\3\2\3\0\14\2\1\52\14\2"+
    "\23\0\3\2\3\0\4\2\1\53\24\2\23\0\3\2"+
    "\3\0\6\2\1\54\1\55\21\2\23\0\3\2\3\0"+
    "\2\2\1\56\7\2\1\57\3\2\1\60\12\2\23\0"+
    "\3\2\3\0\4\2\1\61\24\2\23\0\3\2\3\0"+
    "\7\2\1\62\2\2\1\63\16\2\23\0\3\2\3\0"+
    "\11\2\1\64\17\2\23\0\3\2\3\0\4\2\1\65"+
    "\4\2\1\66\17\2\23\0\3\2\3\0\10\2\1\67"+
    "\1\2\1\70\11\2\1\71\4\2\23\0\3\2\3\0"+
    "\1\2\1\72\27\2\23\0\3\2\3\0\1\2\1\73"+
    "\4\2\1\74\1\75\1\2\1\76\17\2\23\0\3\2"+
    "\3\0\4\2\1\77\24\2\23\0\3\2\3\0\11\2"+
    "\1\100\17\2\23\0\3\2\3\0\6\2\1\101\2\2"+
    "\1\102\17\2\23\0\3\2\3\0\4\2\1\103\4\2"+
    "\1\104\17\2\62\0\1\105\1\106\60\0\1\105\150\0"+
    "\1\107\62\0\1\107\13\0\6\45\1\0\53\45\6\4"+
    "\1\0\53\4\1\0\3\2\3\0\2\2\1\110\2\2"+
    "\1\111\4\2\1\112\16\2\23\0\3\2\3\0\2\2"+
    "\1\113\4\2\1\114\21\2\23\0\3\2\3\0\7\2"+
    "\1\115\21\2\23\0\3\2\3\0\11\2\1\116\17\2"+
    "\23\0\3\2\3\0\5\2\1\117\6\2\1\120\14\2"+
    "\23\0\3\2\3\0\4\2\1\121\24\2\23\0\3\2"+
    "\3\0\3\2\1\122\25\2\23\0\3\2\3\0\4\2"+
    "\1\123\24\2\23\0\3\2\3\0\12\2\1\124\16\2"+
    "\23\0\3\2\3\0\2\2\1\125\7\2\1\126\16\2"+
    "\23\0\3\2\3\0\22\2\1\127\6\2\23\0\3\2"+
    "\3\0\6\2\1\130\22\2\23\0\3\2\3\0\16\2"+
    "\1\131\12\2\23\0\3\2\3\0\12\2\1\132\16\2"+
    "\23\0\3\2\3\0\1\133\30\2\23\0\3\2\3\0"+
    "\14\2\1\134\14\2\23\0\3\2\3\0\14\2\1\135"+
    "\14\2\23\0\3\2\3\0\11\2\1\136\17\2\23\0"+
    "\1\137\2\2\3\0\31\2\23\0\3\2\3\0\17\2"+
    "\1\140\11\2\23\0\3\2\3\0\22\2\1\141\6\2"+
    "\23\0\3\2\3\0\6\2\1\142\22\2\23\0\3\2"+
    "\3\0\7\2\1\143\21\2\23\0\3\2\3\0\12\2"+
    "\1\144\16\2\23\0\3\2\3\0\12\2\1\145\16\2"+
    "\23\0\3\2\3\0\1\146\30\2\23\0\3\2\3\0"+
    "\7\2\1\147\21\2\23\0\3\2\3\0\22\2\1\150"+
    "\6\2\23\0\3\2\3\0\15\2\1\151\13\2\23\0"+
    "\3\2\3\0\3\2\1\152\25\2\23\0\3\2\3\0"+
    "\23\2\1\153\5\2\23\0\3\2\3\0\10\2\1\154"+
    "\13\2\1\155\4\2\23\0\3\2\3\0\3\2\1\156"+
    "\25\2\23\0\3\2\3\0\16\2\1\157\12\2\23\0"+
    "\3\2\3\0\1\2\1\160\27\2\23\0\3\2\3\0"+
    "\12\2\1\161\16\2\23\0\3\2\3\0\6\2\1\162"+
    "\22\2\23\0\3\2\3\0\7\2\1\163\21\2\23\0"+
    "\3\2\3\0\12\2\1\164\16\2\23\0\3\2\3\0"+
    "\7\2\1\165\21\2\23\0\3\2\3\0\1\166\30\2"+
    "\23\0\3\2\3\0\1\2\1\167\27\2\23\0\3\2"+
    "\3\0\3\2\1\170\25\2\23\0\3\2\3\0\11\2"+
    "\1\171\17\2\23\0\3\2\3\0\1\2\1\172\27\2"+
    "\23\0\3\2\3\0\5\2\1\173\23\2\23\0\3\2"+
    "\3\0\5\2\1\174\23\2\23\0\3\2\3\0\1\2"+
    "\1\175\27\2\23\0\3\2\3\0\1\176\30\2\23\0"+
    "\3\2\3\0\6\2\1\177\1\200\21\2\23\0\3\2"+
    "\3\0\7\2\1\201\21\2\23\0\3\2\3\0\1\202"+
    "\30\2\23\0\3\2\3\0\14\2\1\203\14\2\23\0"+
    "\3\2\3\0\11\2\1\204\17\2\23\0\3\2\3\0"+
    "\5\2\1\205\23\2\23\0\3\2\3\0\12\2\1\206"+
    "\16\2\23\0\3\2\3\0\2\2\1\207\26\2\23\0"+
    "\1\210\2\2\3\0\31\2\23\0\3\2\3\0\11\2"+
    "\1\211\17\2\23\0\3\2\3\0\4\2\1\212\24\2"+
    "\23\0\1\213\2\2\3\0\4\2\1\214\24\2\23\0"+
    "\3\2\3\0\23\2\1\215\5\2\23\0\3\2\3\0"+
    "\4\2\1\216\24\2\23\0\3\2\3\0\4\2\1\217"+
    "\24\2\23\0\3\2\3\0\2\2\1\220\26\2\23\0"+
    "\3\2\3\0\14\2\1\221\14\2\23\0\3\2\3\0"+
    "\23\2\1\222\5\2\23\0\3\2\3\0\1\2\1\223"+
    "\27\2\23\0\3\2\3\0\6\2\1\224\22\2\23\0"+
    "\3\2\3\0\14\2\1\225\14\2\23\0\3\2\3\0"+
    "\22\2\1\226\6\2\23\0\3\2\3\0\1\2\1\227"+
    "\27\2\23\0\3\2\3\0\1\230\30\2\23\0\3\2"+
    "\3\0\4\2\1\231\24\2\23\0\3\2\3\0\4\2"+
    "\1\232\24\2\23\0\3\2\3\0\7\2\1\233\21\2"+
    "\23\0\3\2\3\0\4\2\1\234\24\2\23\0\3\2"+
    "\3\0\6\2\1\235\22\2\23\0\3\2\3\0\5\2"+
    "\1\236\23\2\23\0\3\2\3\0\4\2\1\237\24\2"+
    "\23\0\3\2\3\0\6\2\1\240\22\2\23\0\3\2"+
    "\3\0\4\2\1\241\24\2\23\0\3\2\3\0\21\2"+
    "\1\242\7\2\23\0\3\2\3\0\23\2\1\243\5\2"+
    "\23\0\3\2\3\0\6\2\1\244\22\2\23\0\3\2"+
    "\3\0\23\2\1\245\5\2\23\0\3\2\3\0\11\2"+
    "\1\246\17\2\23\0\3\2\3\0\12\2\1\247\16\2"+
    "\23\0\3\2\3\0\6\2\1\250\22\2\23\0\3\2"+
    "\3\0\10\2\1\251\20\2\23\0\3\2\3\0\4\2"+
    "\1\252\24\2\23\0\3\2\3\0\2\2\1\253\5\2"+
    "\1\254\20\2\23\0\3\2\3\0\7\2\1\255\21\2"+
    "\23\0\3\2\3\0\1\2\1\256\27\2\23\0\3\2"+
    "\3\0\11\2\1\257\17\2\23\0\3\2\3\0\15\2"+
    "\1\260\13\2\23\0\3\2\3\0\24\2\1\261\4\2"+
    "\23\0\3\2\3\0\12\2\1\262\16\2\23\0\3\2"+
    "\3\0\5\2\1\263\23\2\23\0\3\2\3\0\12\2"+
    "\1\264\16\2\23\0\3\2\3\0\7\2\1\265\21\2"+
    "\23\0\3\2\3\0\12\2\1\266\16\2\23\0\3\2"+
    "\3\0\7\2\1\267\21\2\23\0\3\2\3\0\7\2"+
    "\1\270\21\2\23\0\3\2\3\0\7\2\1\271\21\2"+
    "\23\0\3\2\3\0\12\2\1\272\16\2\23\0\3\2"+
    "\3\0\4\2\1\273\24\2\23\0\3\2\3\0\2\2"+
    "\1\274\26\2\23\0\3\2\3\0\1\2\1\275\27\2"+
    "\23\0\3\2\3\0\6\2\1\276\22\2\23\0\3\2"+
    "\3\0\6\2\1\277\22\2\23\0\3\2\3\0\10\2"+
    "\1\300\20\2\23\0\3\2\3\0\1\2\1\301\27\2"+
    "\23\0\3\2\3\0\1\2\1\302\27\2\23\0\3\2"+
    "\3\0\1\303\30\2\23\0\3\2\3\0\21\2\1\304"+
    "\7\2\23\0\3\2\3\0\14\2\1\305\14\2\23\0"+
    "\3\2\3\0\7\2\1\306\21\2\23\0\3\2\3\0"+
    "\10\2\1\307\20\2\23\0\1\310\2\2\3\0\31\2"+
    "\23\0\3\2\3\0\4\2\1\311\24\2\23\0\3\2"+
    "\3\0\12\2\1\312\16\2\23\0\3\2\3\0\4\2"+
    "\1\313\24\2\23\0\3\2\3\0\4\2\1\314\24\2"+
    "\23\0\3\2\3\0\6\2\1\315\22\2\23\0\3\2"+
    "\3\0\7\2\1\316\21\2\23\0\3\2\3\0\4\2"+
    "\1\317\24\2\23\0\3\2\3\0\6\2\1\320\22\2"+
    "\23\0\3\2\3\0\4\2\1\321\24\2\23\0\3\2"+
    "\3\0\6\2\1\322\22\2\23\0\3\2\3\0\6\2"+
    "\1\323\22\2\23\0\3\2\3\0\23\2\1\324\5\2"+
    "\23\0\3\2\3\0\14\2\1\325\14\2\23\0\1\326"+
    "\2\2\3\0\31\2\23\0\3\2\3\0\6\2\1\327"+
    "\22\2\23\0\3\2\3\0\6\2\1\330\22\2\23\0"+
    "\3\2\3\0\3\2\1\331\25\2\23\0\3\2\3\0"+
    "\4\2\1\332\24\2\23\0\3\2\3\0\7\2\1\333"+
    "\21\2\23\0\3\2\3\0\7\2\1\334\21\2\23\0"+
    "\3\2\3\0\4\2\1\335\24\2\23\0\3\2\3\0"+
    "\12\2\1\336\16\2\23\0\1\337\2\2\3\0\10\2"+
    "\1\340\20\2\23\0\3\2\3\0\14\2\1\341\14\2"+
    "\23\0\3\2\3\0\6\2\1\342\22\2\23\0\3\2"+
    "\3\0\6\2\1\343\22\2\23\0\3\2\3\0\2\2"+
    "\1\344\26\2\23\0\3\2\3\0\10\2\1\345\20\2"+
    "\23\0\3\2\3\0\1\346\30\2\23\0\3\2\3\0"+
    "\6\2\1\347\22\2\23\0\3\2\3\0\11\2\1\350"+
    "\17\2\23\0\3\2\3\0\7\2\1\351\21\2\23\0"+
    "\3\2\3\0\7\2\1\352\21\2\23\0\3\2\3\0"+
    "\1\353\30\2\23\0\3\2\3\0\7\2\1\354\21\2"+
    "\23\0\3\2\3\0\7\2\1\355\21\2\23\0\3\2"+
    "\3\0\7\2\1\356\21\2\23\0\3\2\3\0\4\2"+
    "\1\357\24\2\23\0\3\2\3\0\1\2\1\360\27\2"+
    "\23\0\3\2\3\0\6\2\1\361\22\2\23\0\3\2"+
    "\3\0\10\2\1\362\20\2\23\0\3\2\3\0\10\2"+
    "\1\363\20\2\23\0\3\2\3\0\6\2\1\364\22\2"+
    "\23\0\3\2\3\0\7\2\1\365\21\2\23\0\1\366"+
    "\2\2\3\0\31\2\23\0\3\2\3\0\10\2\1\367"+
    "\20\2\23\0\3\2\3\0\4\2\1\370\24\2\23\0"+
    "\1\371\2\2\3\0\31\2\23\0\3\2\3\0\23\2"+
    "\1\372\5\2\23\0\3\2\3\0\7\2\1\373\21\2"+
    "\23\0\3\2\3\0\4\2\1\374\24\2\23\0\3\2"+
    "\3\0\4\2\1\375\24\2\23\0\3\2\3\0\4\2"+
    "\1\376\24\2\23\0\3\2\3\0\5\2\1\377\23\2"+
    "\23\0\3\2\3\0\12\2\1\u0100\16\2\23\0\1\u0101"+
    "\2\2\3\0\31\2\23\0\3\2\3\0\1\2\1\u0102"+
    "\27\2\23\0\3\2\3\0\6\2\1\u0103\22\2\23\0"+
    "\1\u0104\2\2\3\0\31\2\23\0\3\2\3\0\7\2"+
    "\1\u0105\21\2\23\0\3\2\3\0\7\2\1\u0106\21\2"+
    "\23\0\1\u0107\2\2\3\0\31\2\23\0\3\2\3\0"+
    "\5\2\1\u0108\23\2\23\0\3\2\3\0\11\2\1\u0109"+
    "\17\2\23\0\1\u010a\2\2\3\0\31\2\23\0\3\2"+
    "\3\0\12\2\1\u010b\16\2\23\0\3\2\3\0\15\2"+
    "\1\u010c\13\2\23\0\3\2\3\0\7\2\1\u010d\21\2"+
    "\23\0\1\u010e\2\2\3\0\30\2\1\u010f\23\0\3\2"+
    "\3\0\12\2\1\u0110\16\2\23\0\3\2\3\0\2\2"+
    "\1\u0111\26\2\23\0\3\2\3\0\1\2\1\u0112\27\2"+
    "\23\0\3\2\3\0\11\2\1\u0113\17\2\23\0\3\2"+
    "\3\0\14\2\1\u0114\14\2\23\0\3\2\3\0\26\2"+
    "\1\u0115\2\2\23\0\3\2\3\0\7\2\1\u0116\21\2"+
    "\23\0\3\2\3\0\7\2\1\u0117\21\2\23\0\3\2"+
    "\3\0\6\2\1\u0118\5\2\1\u0119\14\2\23\0\1\u011a"+
    "\2\2\3\0\31\2\23\0\3\2\3\0\1\u011b\30\2"+
    "\23\0\3\2\3\0\7\2\1\u011c\21\2\23\0\3\2"+
    "\3\0\7\2\1\u011d\21\2\23\0\3\2\3\0\5\2"+
    "\1\u011e\2\2\1\u011f\20\2\23\0\3\2\3\0\4\2"+
    "\1\u0120\24\2\23\0\3\2\3\0\4\2\1\u0121\24\2"+
    "\23\0\3\2\3\0\6\2\1\u0122\22\2\23\0\3\2"+
    "\3\0\6\2\1\u0123\22\2\23\0\3\2\3\0\7\2"+
    "\1\u0124\21\2\23\0\3\2\3\0\6\2\1\u0125\22\2"+
    "\23\0\3\2\3\0\22\2\1\u0126\6\2\23\0\3\2"+
    "\3\0\12\2\1\u0127\16\2\23\0\3\2\3\0\10\2"+
    "\1\u0128\20\2\23\0\3\2\3\0\7\2\1\u0129\21\2"+
    "\23\0\3\2\3\0\6\2\1\u012a\22\2\23\0\3\2"+
    "\3\0\11\2\1\u012b\17\2\23\0\1\u012c\2\2\3\0"+
    "\31\2\23\0\3\2\3\0\5\2\1\u012d\23\2\23\0"+
    "\3\2\3\0\1\2\1\u012e\27\2\23\0\3\2\3\0"+
    "\14\2\1\u012f\14\2\23\0\3\2\3\0\25\2\1\u0130"+
    "\3\2\23\0\3\2\3\0\11\2\1\u0131\17\2\23\0"+
    "\3\2\3\0\7\2\1\u0132\21\2\23\0\3\2\3\0"+
    "\11\2\1\u0133\17\2\23\0\3\2\3\0\4\2\1\u0134"+
    "\24\2\23\0\3\2\3\0\1\u0135\30\2\23\0\3\2"+
    "\3\0\12\2\1\u0136\16\2\23\0\1\u0137\2\2\3\0"+
    "\31\2\23\0\3\2\3\0\23\2\1\u0138\5\2\23\0"+
    "\3\2\3\0\1\2\1\u0139\27\2\23\0\3\2\3\0"+
    "\5\2\1\u013a\23\2\23\0\3\2\3\0\1\2\1\u013b"+
    "\27\2\23\0\3\2\3\0\11\2\1\u013c\17\2\23\0"+
    "\3\2\3\0\6\2\1\u013d\22\2\23\0\3\2\3\0"+
    "\22\2\1\u013e\6\2\23\0\3\2\3\0\10\2\1\u013f"+
    "\20\2\23\0\3\2\3\0\11\2\1\u0140\17\2\23\0"+
    "\3\2\3\0\15\2\1\u0141\13\2\23\0\3\2\3\0"+
    "\17\2\1\u0142\11\2\23\0\3\2\3\0\6\2\1\u0143"+
    "\22\2\23\0\3\2\3\0\4\2\1\u0144\24\2\23\0"+
    "\3\2\3\0\10\2\1\u0145\20\2\23\0\3\2\3\0"+
    "\1\2\1\u0146\27\2\23\0\3\2\3\0\13\2\1\u0147"+
    "\15\2\23\0\3\2\3\0\12\2\1\u0148\16\2\23\0"+
    "\3\2\3\0\4\2\1\u0149\24\2\23\0\3\2\3\0"+
    "\6\2\1\u014a\22\2\23\0\3\2\3\0\14\2\1\u014b"+
    "\14\2\23\0\3\2\3\0\14\2\1\u014c\14\2\23\0"+
    "\3\2\3\0\16\2\1\u014d\12\2\23\0\3\2\3\0"+
    "\11\2\1\u014e\17\2\23\0\3\2\3\0\5\2\1\u014f"+
    "\23\2\23\0\3\2\3\0\10\2\1\u0150\20\2\23\0"+
    "\3\2\3\0\10\2\1\u0151\20\2\23\0\3\2\3\0"+
    "\5\2\1\u0152\23\2\23\0\3\2\3\0\7\2\1\u0153"+
    "\21\2\23\0\3\2\3\0\6\2\1\u0154\22\2\23\0"+
    "\3\2\3\0\11\2\1\u0155\17\2\23\0\3\2\3\0"+
    "\22\2\1\u0156\6\2\23\0\3\2\3\0\20\2\1\u0157"+
    "\10\2\23\0\3\2\3\0\11\2\1\u0158\17\2\23\0"+
    "\3\2\3\0\7\2\1\u0159\21\2\23\0\3\2\3\0"+
    "\4\2\1\u015a\24\2\23\0\3\2\3\0\14\2\1\u015b"+
    "\14\2\23\0\3\2\3\0\6\2\1\u015c\22\2\23\0"+
    "\3\2\3\0\5\2\1\u015d\23\2\23\0\3\2\3\0"+
    "\6\2\1\u015e\22\2\23\0\3\2\3\0\1\2\1\u015f"+
    "\27\2\23\0\3\2\3\0\10\2\1\u0160\20\2\23\0"+
    "\3\2\3\0\1\2\1\u0161\27\2\23\0\3\2\3\0"+
    "\6\2\1\u0162\22\2\23\0\3\2\3\0\7\2\1\u0163"+
    "\21\2\23\0\3\2\3\0\22\2\1\u0164\6\2\23\0"+
    "\3\2\3\0\12\2\1\u0165\16\2\23\0\3\2\3\0"+
    "\5\2\1\u0166\23\2\23\0\3\2\3\0\1\2\1\u0167"+
    "\27\2\23\0\3\2\3\0\7\2\1\u0168\21\2\23\0"+
    "\3\2\3\0\11\2\1\u0169\17\2\23\0\3\2\3\0"+
    "\1\u016a\30\2\23\0\3\2\3\0\6\2\1\u016b\22\2"+
    "\23\0\3\2\3\0\5\2\1\u016c\23\2\23\0\3\2"+
    "\3\0\11\2\1\u016d\17\2\23\0\3\2\3\0\22\2"+
    "\1\u016e\6\2\23\0\3\2\3\0\2\2\1\u016f\26\2"+
    "\23\0\3\2\3\0\10\2\1\u0170\20\2\23\0\3\2"+
    "\3\0\27\2\1\u0171\1\2\23\0\3\2\3\0\1\2"+
    "\1\u0172\27\2\23\0\3\2\3\0\11\2\1\u0173\17\2"+
    "\23\0\3\2\3\0\10\2\1\u0174\20\2\23\0\3\2"+
    "\3\0\6\2\1\u0175\22\2\23\0\3\2\3\0\20\2"+
    "\1\u0176\10\2\23\0\3\2\3\0\10\2\1\u0177\20\2"+
    "\23\0\3\2\3\0\1\2\1\u0178\27\2\23\0\3\2"+
    "\3\0\1\u0179\30\2\23\0\3\2\3\0\10\2\1\u017a"+
    "\20\2\23\0\3\2\3\0\5\2\1\u017b\23\2\23\0"+
    "\3\2\3\0\6\2\1\u017c\22\2\23\0\3\2\3\0"+
    "\4\2\1\u017d\24\2\23\0\3\2\3\0\7\2\1\u017e"+
    "\21\2\23\0\3\2\3\0\14\2\1\u017f\14\2\23\0"+
    "\3\2\3\0\6\2\1\u0180\22\2\23\0\3\2\3\0"+
    "\14\2\1\u0181\14\2\23\0\3\2\3\0\6\2\1\u0182"+
    "\22\2\23\0\3\2\3\0\14\2\1\u0183\14\2\23\0"+
    "\3\2\3\0\2\2\1\u0184\26\2\23\0\3\2\3\0"+
    "\11\2\1\u0185\17\2\23\0\3\2\3\0\1\2\1\u0186"+
    "\27\2\23\0\3\2\3\0\21\2\1\u0187\7\2\23\0"+
    "\3\2\3\0\4\2\1\u0188\24\2\23\0\3\2\3\0"+
    "\6\2\1\u0189\22\2\23\0\3\2\3\0\22\2\1\u018a"+
    "\6\2\23\0\3\2\3\0\10\2\1\u018b\20\2\23\0"+
    "\3\2\3\0\6\2\1\u018c\22\2\23\0\3\2\3\0"+
    "\1\u018d\30\2\23\0\3\2\3\0\1\2\1\u018e\27\2"+
    "\23\0\3\2\3\0\10\2\1\u018f\20\2\23\0\3\2"+
    "\3\0\1\2\1\u0190\27\2\23\0\3\2\3\0\5\2"+
    "\1\u0191\23\2\23\0\3\2\3\0\1\2\1\u0192\27\2"+
    "\23\0\3\2\3\0\10\2\1\u0193\20\2\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[17350];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\1\1\0\23\1\1\11\1\1\2\0\11\11"+
    "\1\1\1\11\1\0\35\1\3\11\u014c\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[403];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 26: 
          { return symbol(sym.REGLA);
          }
        case 66: break;
        case 25: 
          { return symbol(sym.ARBOL);
          }
        case 67: break;
        case 55: 
          { return symbol(sym.CONSTRUIR_TABLA);
          }
        case 68: break;
        case 32: 
          { return symbol(sym.TOKENS);
          }
        case 69: break;
        case 44: 
          { return symbol(sym.PRINCIPAL);
          }
        case 70: break;
        case 49: 
          { return symbol(sym.FIN_MIENTRAS);
          }
        case 71: break;
        case 47: 
          { return symbol(sym.EJECUTARPROG);
          }
        case 72: break;
        case 64: 
          { return symbol(sym.ANALISIS_SINTACTICO);
          }
        case 73: break;
        case 2: 
          { return symbol(sym.NUMERO, Integer.parseInt(yytext()));
          }
        case 74: break;
        case 31: 
          { return symbol(sym.INICIO);
          }
        case 75: break;
        case 1: 
          { return symbol(sym.ID, yytext());
          }
        case 76: break;
        case 59: 
          { return symbol(sym.ESTRUCTURA_TABLA);
          }
        case 77: break;
        case 37: 
          { return symbol(sym.ESTADOS);
          }
        case 78: break;
        case 54: 
          { return symbol(sym.DEFINIR_TOKENS);
          }
        case 79: break;
        case 29: 
          { return symbol(sym.VACIO);
          }
        case 80: break;
        case 61: 
          { return symbol(sym.EJECUTAR_AUTOMATA);
          }
        case 81: break;
        case 36: 
          { return symbol(sym.SECCION);
          }
        case 82: break;
        case 8: 
          { return symbol(sym.LLAVE_ABRE);
          }
        case 83: break;
        case 11: 
          { return symbol(sym.PAREN_CIERRA);
          }
        case 84: break;
        case 24: 
          { return symbol(sym.LINEA);
          }
        case 85: break;
        case 56: 
          { return symbol(sym.LIMPIAR_ERRORES);
          }
        case 86: break;
        case 23: 
          { return symbol(sym.CAMPO);
          }
        case 87: break;
        case 3: 
          { /* ignorar */
          }
        case 88: break;
        case 58: 
          { return symbol(sym.ESTADOS_FINALES);
          }
        case 89: break;
        case 5: 
          { return symbol(sym.OPE_RELACIONAL);
          }
        case 90: break;
        case 19: 
          { return symbol(sym.SI);
          }
        case 91: break;
        case 28: 
          { return symbol(sym.TABLA);
          }
        case 92: break;
        case 22: 
          { return symbol(sym.SINO);
          }
        case 93: break;
        case 48: 
          { return symbol(sym.TRANSICIONES);
          }
        case 94: break;
        case 9: 
          { return symbol(sym.LLAVE_CIERRA);
          }
        case 95: break;
        case 6: 
          { return symbol(sym.OPE_ARITMETICO);
          }
        case 96: break;
        case 34: 
          { return symbol(sym.COLUMNA);
          }
        case 97: break;
        case 33: 
          { return symbol(sym.FIN_SI);
          }
        case 98: break;
        case 13: 
          { return symbol(sym.CORCHETE_CIERRA);
          }
        case 99: break;
        case 20: 
          { { return symbol(sym.OPE_TRANSICION); }
          }
        case 100: break;
        case 46: 
          { return symbol(sym.VER_ERRORES);
          }
        case 101: break;
        case 43: 
          { return symbol(sym.IMPRIMIR);
          }
        case 102: break;
        case 15: 
          { return symbol(sym.DOS_PUNTOS);
          }
        case 103: break;
        case 10: 
          { return symbol(sym.PAREN_ABRE);
          }
        case 104: break;
        case 60: 
          { return symbol(sym.DEFINIR_ALFABETO);
          }
        case 105: break;
        case 14: 
          { return symbol(sym.COMA);
          }
        case 106: break;
        case 62: 
          { return symbol(sym.VERIFICAR_ERRORES);
          }
        case 107: break;
        case 52: 
          { return symbol(sym.ESTADO_INICIAL);
          }
        case 108: break;
        case 7: 
          { return symbol(sym.OPE_LOGICO);
          }
        case 109: break;
        case 35: 
          { return symbol(sym.IGNORAR);
          }
        case 110: break;
        case 27: 
          { return symbol(sym.TOKEN);
          }
        case 111: break;
        case 53: 
          { return symbol(sym.TABLA_SIMBOLOS);
          }
        case 112: break;
        case 4: 
          { return symbol(sym.OPE_ASIGNACION);
          }
        case 113: break;
        case 42: 
          { return symbol(sym.MIENTRAS);
          }
        case 114: break;
        case 57: 
          { return symbol(sym.ANALISIS_LEXICO);
          }
        case 115: break;
        case 30: 
          { return symbol(sym.PATRON);
          }
        case 116: break;
        case 50: 
          { return symbol(sym.NO_TERMINALES);
          }
        case 117: break;
        case 45: 
          { return symbol(sym.TERMINALES);
          }
        case 118: break;
        case 41: 
          { return symbol(sym.CONJUNTO);
          }
        case 119: break;
        case 12: 
          { return symbol(sym.CORCHETE_ABRE);
          }
        case 120: break;
        case 16: 
          { return symbol(sym.PUNTO_COMA);
          }
        case 121: break;
        case 21: 
          { return symbol(sym.OTRO);
          }
        case 122: break;
        case 51: 
          { return symbol(sym.CARGAR_ARCHIVO);
          }
        case 123: break;
        case 17: 
          { /* comentario */
          }
        case 124: break;
        case 18: 
          { return symbol(sym.CADENA, yytext());
          }
        case 125: break;
        case 65: 
          { return symbol(sym.GENERAR_TS);
          }
        case 126: break;
        case 40: 
          { return symbol(sym.COMPILAR);
          }
        case 127: break;
        case 38: 
          { return symbol(sym.ENTRADA);
          }
        case 128: break;
        case 39: 
          { return symbol(sym.DIBUJAR);
          }
        case 129: break;
        case 63: 
          { return symbol(sym.PALABRAS_RESERVADAS);
          }
        case 130: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
