/* The following code was generated by JFlex 1.4.3 on 18/11/25, 21:41 */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 18/11/25, 21:41 from the specification file
 * <tt>C:/Users/alanc/OneDrive/Documents/Tec/11vo Semestre/Lenguajes y Automatas 1/Unidad 4/Proyecto Compilador/quimcode-compilador/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\10\2\0\1\2\22\0\1\2\1\46\1\6\1\11"+
    "\1\0\1\26\1\50\1\0\1\52\1\52\1\5\1\5\1\53\1\5"+
    "\1\4\1\5\12\3\1\53\1\52\1\47\1\45\1\47\2\0\2\1"+
    "\1\20\1\1\1\1\5\1\1\20\1\20\1\20\2\1\1\23\12\1"+
    "\1\52\1\7\1\52\1\0\1\12\1\0\1\21\1\24\1\35\1\40"+
    "\1\33\1\32\1\16\1\34\1\30\1\44\1\17\1\15\1\13\1\31"+
    "\1\14\1\36\1\41\1\25\1\27\1\22\1\37\1\43\1\1\2\1"+
    "\1\42\1\52\1\51\1\52\103\0\1\53\7\0\1\53\3\0\1\53"+
    "\3\0\1\53\1\0\1\53\6\0\1\53\1\0\1\53\4\0\1\53"+
    "\7\0\1\53\3\0\1\53\3\0\1\53\1\0\1\53\6\0\1\53"+
    "\1\0\1\53\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\3\1\10\6\2\1\5\11\2\1\11\1\12\1\13"+
    "\2\1\1\14\1\10\1\15\1\10\1\16\3\10\1\16"+
    "\1\15\1\17\1\20\1\7\1\0\12\2\1\21\20\2"+
    "\1\13\1\12\1\4\4\10\1\0\43\2\4\0\15\2"+
    "\1\21\15\2\1\21\2\2\4\0\42\2\1\21\27\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0294"+
    "\0\54\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8"+
    "\0\u03f4\0\u0420\0\u044c\0\u044c\0\u044c\0\u0478\0\u04a4\0\54"+
    "\0\u04d0\0\u04fc\0\u0528\0\u04d0\0\u0554\0\u0580\0\u05ac\0\54"+
    "\0\334\0\u05d8\0\54\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4"+
    "\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814"+
    "\0\u0840\0\u086c\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974"+
    "\0\u09a0\0\u09cc\0\u09f8\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4"+
    "\0\54\0\54\0\u0b00\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc"+
    "\0\u0c08\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c"+
    "\0\u0d68\0\u0d94\0\u0dc0\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\u0e9c"+
    "\0\u0ec8\0\u0ef4\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4\0\u0fd0\0\u0ffc"+
    "\0\u1028\0\u1054\0\u1080\0\u10ac\0\u10d8\0\u1104\0\u1130\0\u115c"+
    "\0\u1188\0\u11b4\0\u11e0\0\u120c\0\u1238\0\u1264\0\u1290\0\u12bc"+
    "\0\u12e8\0\u1314\0\u1340\0\u136c\0\u1398\0\u13c4\0\u13f0\0\u141c"+
    "\0\u1448\0\u1474\0\u14a0\0\u14cc\0\u14f8\0\u1524\0\u1550\0\u157c"+
    "\0\u15a8\0\u15d4\0\u1600\0\u162c\0\u1658\0\u1684\0\u16b0\0\u16dc"+
    "\0\u1708\0\u1734\0\130\0\u1760\0\u178c\0\u17b8\0\u17e4\0\u1810"+
    "\0\u183c\0\u1868\0\u1894\0\u18c0\0\u18ec\0\u1918\0\u1944\0\u1970"+
    "\0\u199c\0\u19c8\0\u19f4\0\u1a20\0\u1a4c\0\u1a78\0\u1aa4\0\u1ad0"+
    "\0\u1afc\0\u1b28\0\u1b54\0\u1b80\0\u1bac\0\u1bd8\0\u1c04\0\u1c30"+
    "\0\u1c5c\0\u1c88\0\u1cb4\0\u1ce0\0\u1d0c\0\u1d38\0\u1d64\0\u1d90"+
    "\0\u1dbc\0\u1de8\0\u1e14\0\u1e40\0\u1e6c\0\u1e98\0\u1ec4\0\u1ef0"+
    "\0\u1f1c\0\u1f48\0\u1f74\0\u1fa0\0\u1fcc\0\u1ff8\0\u2024\0\u2050"+
    "\0\u207c\0\u20a8\0\u20d4\0\u2100\0\u212c\0\u2158\0\u2184\0\u21b0"+
    "\0\u21dc\0\u2208\0\u2234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\4\1\11\1\12\1\13\1\3\1\14\1\15\2\3"+
    "\1\16\2\3\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\3\1\32\4\3"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\21\55\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\16\3\11\0"+
    "\1\4\5\0\1\4\44\0\1\41\1\0\1\5\1\42"+
    "\5\0\1\41\1\43\2\41\1\44\1\45\1\44\1\46"+
    "\2\41\1\47\1\41\1\50\16\41\12\0\1\51\51\0"+
    "\1\52\10\0\14\52\1\0\16\52\7\0\6\10\1\53"+
    "\1\54\1\55\43\10\10\11\1\0\43\11\1\0\1\3"+
    "\1\0\1\41\6\0\1\41\13\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\2\3\1\56\11\3\1\0"+
    "\1\3\1\57\2\3\1\60\11\3\10\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\3\1\61\14\3\10\0"+
    "\1\3\1\0\1\3\6\0\7\3\1\62\4\3\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\4\3\1\63"+
    "\7\3\1\0\6\3\1\64\7\3\10\0\1\3\1\0"+
    "\1\3\6\0\7\3\1\65\4\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\4\3\1\66"+
    "\11\3\10\0\1\3\1\0\1\3\6\0\2\3\1\67"+
    "\11\3\1\0\1\3\1\70\14\3\10\0\1\3\1\0"+
    "\1\3\6\0\1\3\1\71\12\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\4\3\1\72"+
    "\11\3\10\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\3\1\73\14\3\10\0\1\3\1\0\1\3\6\0"+
    "\3\3\1\74\10\3\1\0\1\75\1\3\1\76\11\3"+
    "\1\77\1\100\10\0\1\3\1\0\1\3\6\0\7\3"+
    "\1\101\4\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\2\3\1\102\4\3\1\103\4\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\13\3\1\104\1\0"+
    "\4\3\1\105\11\3\10\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\106\2\3\1\107\3\3\1\110"+
    "\5\3\10\0\1\52\10\0\14\52\1\0\16\52\1\111"+
    "\7\0\1\52\10\0\14\52\1\0\16\52\3\0\1\112"+
    "\54\0\1\112\3\0\1\41\1\0\1\41\6\0\14\41"+
    "\1\0\16\41\12\0\1\113\51\0\1\41\1\0\1\41"+
    "\6\0\2\41\1\114\1\44\10\41\1\0\16\41\10\0"+
    "\1\41\1\0\1\41\6\0\4\41\1\44\4\41\1\115"+
    "\2\41\1\0\16\41\10\0\1\41\1\0\1\41\6\0"+
    "\10\41\1\116\3\41\1\0\16\41\10\0\1\41\1\0"+
    "\1\41\6\0\7\41\1\117\4\41\1\0\16\41\10\0"+
    "\1\52\1\0\1\52\6\0\14\52\1\0\16\52\7\0"+
    "\6\10\1\55\1\10\1\0\43\10\6\55\1\53\1\120"+
    "\44\55\1\0\1\3\1\0\1\3\6\0\3\3\1\121"+
    "\10\3\1\0\1\122\15\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\4\3\1\123\11\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\11\3\1\124\1\3"+
    "\1\125\2\3\10\0\1\3\1\0\1\3\6\0\1\3"+
    "\1\126\6\3\1\127\3\3\1\0\12\3\1\130\3\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\1\131"+
    "\15\3\10\0\1\3\1\0\1\3\6\0\13\3\1\132"+
    "\1\0\1\3\1\133\14\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\10\3\1\134\5\3\10\0\1\3"+
    "\1\0\1\3\6\0\3\3\1\135\10\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\7\3\1\136\4\3"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\3\3"+
    "\1\137\10\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\2\3\1\140\13\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\7\3\1\141\6\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\10\3"+
    "\1\142\5\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\2\3\1\143\13\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\144\2\3\1\145\11\3"+
    "\10\0\1\3\1\0\1\3\6\0\10\3\1\146\3\3"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\3\3\1\147\10\3\1\150\1\3\10\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\151\4\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\4\3"+
    "\1\152\11\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\6\3\1\153\7\3\10\0\1\3\1\0\1\3"+
    "\6\0\1\3\1\154\12\3\1\0\16\3\10\0\1\3"+
    "\1\0\1\3\6\0\3\3\1\155\10\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\1\3"+
    "\1\156\2\3\1\157\11\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\160\15\3\10\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\161\15\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\162\15\3\10\0"+
    "\1\3\1\0\1\3\6\0\13\3\1\163\1\0\16\3"+
    "\12\0\1\113\7\0\1\164\2\0\1\50\1\165\1\50"+
    "\1\166\2\0\1\167\1\0\1\50\26\0\1\41\1\0"+
    "\1\41\6\0\3\41\1\44\10\41\1\0\16\41\10\0"+
    "\1\41\1\0\1\41\6\0\7\41\1\44\4\41\1\0"+
    "\16\41\10\0\1\41\1\0\1\41\6\0\1\41\1\44"+
    "\12\41\1\0\16\41\10\0\1\41\1\0\1\41\6\0"+
    "\13\41\1\44\1\0\16\41\7\0\10\55\1\0\43\55"+
    "\1\0\1\3\1\0\1\3\6\0\14\3\1\0\4\3"+
    "\1\170\11\3\10\0\1\3\1\0\1\3\6\0\10\3"+
    "\1\171\3\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\2\3\1\172\13\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\3\1\173\14\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\6\3"+
    "\1\174\7\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\7\3\1\175\6\3\10\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\176\1\0\16\3\10\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\10\3\1\177\5\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\4\3\1\134"+
    "\11\3\10\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\4\3\1\200\11\3\10\0\1\3\1\0\1\3\6\0"+
    "\10\3\1\201\3\3\1\0\16\3\10\0\1\3\1\0"+
    "\1\3\6\0\2\3\1\105\11\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\7\3\1\202\4\3\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\6\3\1\203\7\3\10\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\204\6\3\1\203\5\3\10\0"+
    "\1\3\1\0\1\3\6\0\2\3\1\205\11\3\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\13\3\1\206"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\10\3"+
    "\1\207\3\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\1\210\13\3\1\0\16\3\10\0\1\3\1\0"+
    "\1\3\6\0\1\3\1\211\12\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\1\3\1\212\12\3\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\7\3\1\204"+
    "\4\3\1\0\16\3\10\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\175\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\213\14\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\7\3\1\214\6\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\6\3"+
    "\1\215\7\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\4\3\1\216\11\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\7\3\1\217\6\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\4\3\1\220\11\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\2\3"+
    "\1\221\13\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\6\3\1\222\7\3\10\0\1\3\1\0\1\3"+
    "\6\0\2\3\1\223\11\3\1\0\16\3\10\0\1\3"+
    "\1\0\1\3\6\0\2\3\1\224\11\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\10\3\1\225\3\3"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\7\3"+
    "\1\203\4\3\1\0\16\3\23\0\1\226\1\50\54\0"+
    "\1\50\4\0\1\227\52\0\1\230\52\0\1\231\33\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\223\15\3"+
    "\10\0\1\3\1\0\1\3\6\0\13\3\1\232\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\10\3\1\233"+
    "\3\3\1\0\16\3\10\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\234\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\3\3\1\201\10\3\1\0\16\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\3\1\201\14\3"+
    "\10\0\1\3\1\0\1\3\6\0\2\3\1\170\11\3"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\1\3\1\204\14\3\10\0\1\3\1\0\1\3"+
    "\6\0\4\3\1\201\7\3\1\0\16\3\10\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\216\4\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\2\3"+
    "\1\235\13\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\6\3\1\236\7\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\11\3\1\160\4\3\10\0\1\3"+
    "\1\0\1\3\6\0\1\237\13\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\3\1\240"+
    "\14\3\10\0\1\3\1\0\1\3\6\0\13\3\1\241"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\1\3"+
    "\1\242\12\3\1\0\1\243\6\3\1\244\6\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\3\1\245"+
    "\14\3\10\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\4\3\1\246\11\3\10\0\1\3\1\0\1\3\6\0"+
    "\7\3\1\247\4\3\1\0\16\3\10\0\1\3\1\0"+
    "\1\3\6\0\2\3\1\250\11\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\10\3\1\251"+
    "\5\3\10\0\1\3\1\0\1\3\6\0\13\3\1\223"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\10\3\1\252\5\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\2\3\1\133\13\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\6\3\1\253\7\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\1\3"+
    "\1\254\14\3\10\0\1\3\1\0\1\3\6\0\3\3"+
    "\1\255\10\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\174\14\3\24\0\1\50"+
    "\57\0\1\50\45\0\1\50\65\0\1\50\27\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\256\4\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\13\3\1\257\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\1\260\13\3"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\6\3\1\261\7\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\262\14\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\243\15\3\10\0"+
    "\1\3\1\0\1\3\6\0\1\3\1\263\12\3\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\7\3\1\264"+
    "\4\3\1\0\16\3\10\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\57\14\3\10\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\3\1\223\14\3\10\0"+
    "\1\3\1\0\1\3\6\0\13\3\1\265\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\2\3"+
    "\1\201\13\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\2\3\1\266\13\3\10\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\267\1\0\16\3\10\0\1\3\1\0"+
    "\1\3\6\0\13\3\1\201\1\0\16\3\10\0\1\3"+
    "\1\0\1\3\6\0\10\3\1\270\3\3\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\4\3"+
    "\1\271\11\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\1\3\1\272\14\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\7\3\1\273\6\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\14\3\1\153\1\3"+
    "\10\0\1\3\1\0\1\3\6\0\13\3\1\274\1\0"+
    "\16\3\10\0\1\3\1\0\1\3\6\0\7\3\1\170"+
    "\4\3\1\0\16\3\10\0\1\3\1\0\1\3\6\0"+
    "\10\3\1\275\3\3\1\0\7\3\1\276\6\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\4\3\1\270"+
    "\11\3\10\0\1\3\1\0\1\3\6\0\2\3\1\277"+
    "\11\3\1\0\16\3\10\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\216\14\3\10\0\1\3\1\0"+
    "\1\3\6\0\3\3\1\300\10\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\3\1\156"+
    "\14\3\10\0\1\3\1\0\1\3\6\0\10\3\1\160"+
    "\3\3\1\0\16\3\10\0\1\3\1\0\1\3\6\0"+
    "\1\301\13\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\7\3\1\302\4\3\1\0\16\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\266\15\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\7\3\1\303"+
    "\6\3\10\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\3\1\133\14\3\10\0\1\3\1\0\1\3\6\0"+
    "\1\304\13\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\4\3\1\305\11\3\10\0\1\3"+
    "\1\0\1\3\6\0\13\3\1\306\1\0\5\3\1\223"+
    "\10\3\10\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\2\3\1\223\13\3\10\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\307\14\3\10\0\1\3\1\0"+
    "\1\3\6\0\7\3\1\310\4\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\13\3\1\311\1\0\16\3"+
    "\10\0\1\3\1\0\1\3\6\0\7\3\1\312\4\3"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\1\3\1\313\14\3\10\0\1\3\1\0\1\3"+
    "\6\0\1\3\1\314\12\3\1\0\16\3\10\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\4\3\1\315\11\3"+
    "\10\0\1\3\1\0\1\3\6\0\14\3\1\0\13\3"+
    "\1\201\2\3\10\0\1\3\1\0\1\3\6\0\3\3"+
    "\1\316\10\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\1\317\13\3\1\0\16\3\10\0\1\3\1\0"+
    "\1\3\6\0\3\3\1\223\10\3\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\2\3\1\320"+
    "\13\3\10\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\7\3\1\223\6\3\10\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\236\15\3\10\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\4\3\1\321\11\3\10\0\1\3"+
    "\1\0\1\3\6\0\13\3\1\20\1\0\16\3\10\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\3\3\1\160"+
    "\12\3\10\0\1\3\1\0\1\3\6\0\13\3\1\322"+
    "\1\0\16\3\10\0\1\3\1\0\1\3\6\0\10\3"+
    "\1\323\3\3\1\0\16\3\10\0\1\3\1\0\1\3"+
    "\6\0\7\3\1\223\4\3\1\0\16\3\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\16\1\1\11\16\1\1\11\7\1\1\11"+
    "\2\1\1\11\1\1\1\0\33\1\2\11\5\1\1\0"+
    "\43\1\4\0\36\1\4\0\72\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private final TablaSimbolos tablaSimbolos = new TablaSimbolos();
    private final TablaFunciones tablaFunciones = new TablaFunciones();

    public TablaSimbolos getTablaSimbolos() {
        return this.tablaSimbolos;
    }

    public TablaFunciones getTablaFunciones() { 
        return this.tablaFunciones;
    }

    private Tokens token(String lex, String comp, int li, int c){
        return new Tokens(lex, comp, li+1, c+1); 
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return token(yytext(),"OPE_LOGICO",yyline,yycolumn);
          }
        case 18: break;
        case 9: 
          { return token(yytext(),"OPE_ASIGNACION",yyline,yycolumn);
          }
        case 19: break;
        case 12: 
          { return token(yytext(),"DELIMITADOR",yyline,yycolumn);
          }
        case 20: break;
        case 17: 
          { return token(yytext(),"PALABRA_RESERVADA",yyline,yycolumn);
          }
        case 21: break;
        case 13: 
          { return token(yytext(),"ERROR_NUMERO_MALFORMADO",yyline,yycolumn);
          }
        case 22: break;
        case 7: 
          { return token(yytext(),"ERROR_CADENA_NO_CERRADA",yyline,yycolumn);
          }
        case 23: break;
        case 1: 
          { return token(yytext(),"ERROR_CARACTER_INVALIDO",yyline,yycolumn);
          }
        case 24: break;
        case 14: 
          { return token(yytext(),"LIT_NUMERICA",yyline,yycolumn);
          }
        case 25: break;
        case 16: 
          { return token(yytext(),"CADENA",yyline,yycolumn);
          }
        case 26: break;
        case 5: 
          { return token(yytext(), "ERROR", yyline, yycolumn);
          }
        case 27: break;
        case 2: 
          { // Revisa la "Tabla Fija"
        if (TablaPalabrasReservadas.esReservada(yytext())){
            return token(yytext(),"ERROR_IDENTIFICADOR_ES_PALABRA_RESERVADA",yyline,yycolumn);
        } else {
            // Si no es reservada, la registra en la "Tabla de identificadores"
            tablaSimbolos.registrarIdentificador(yytext(), yyline+1, yycolumn+1);
            return token(yytext(),"IDENTIFICADOR",yyline,yycolumn);
        }
          }
        case 28: break;
        case 8: 
          { return token(yytext(), "ERROR_IDENTIFICADOR_INVALIDO", yyline, yycolumn);
          }
        case 29: break;
        case 3: 
          { /* ignorar */
          }
        case 30: break;
        case 15: 
          { return token(yytext(), "ERROR_LEXICO", yyline, yycolumn);
          }
        case 31: break;
        case 4: 
          { return token(yytext(),"NUMERO",yyline,yycolumn);
          }
        case 32: break;
        case 6: 
          { return token(yytext(),"OPE_ARITMETICO",yyline,yycolumn);
          }
        case 33: break;
        case 11: 
          { return token(yytext(),"OPE_RELACIONAL",yyline,yycolumn);
          }
        case 34: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
