/* The following code was generated by JFlex 1.4.3 on 27/11/25 21:00 */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/11/25 21:00 from the specification file
 * <tt>C:/Users/alanc/OneDrive/Documents/Tec/11vo Semestre/Lenguajes y Automatas 1/U4/quimcode-compilador/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\10\2\0\1\3\22\0\1\3\1\42\1\6\1\11"+
    "\1\0\1\52\1\44\1\0\1\46\1\46\1\40\1\40\1\47\1\51"+
    "\1\5\1\51\12\4\1\50\1\46\1\43\1\41\1\43\2\0\32\2"+
    "\1\46\1\7\1\46\1\0\1\1\1\0\1\23\1\34\1\26\1\33"+
    "\1\20\1\16\1\30\1\37\1\13\1\36\1\31\1\24\1\17\1\14"+
    "\1\15\1\27\1\2\1\22\1\12\1\21\1\35\1\32\1\2\1\25"+
    "\2\2\1\46\1\45\1\46\103\0\1\52\7\0\1\52\3\0\1\52"+
    "\3\0\1\52\1\0\1\52\6\0\1\52\1\0\1\52\4\0\1\52"+
    "\7\0\1\52\3\0\1\52\3\0\1\52\1\0\1\52\6\0\1\52"+
    "\1\0\1\52\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\4\16\3\1\10\1\11\1\12\1\13\1\1\2\14"+
    "\3\6\1\2\2\15\1\16\1\7\1\0\1\17\25\3"+
    "\1\20\1\13\1\12\1\5\1\0\27\3\1\17\32\3"+
    "\1\17\56\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285"+
    "\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd"+
    "\0\u0408\0\u0408\0\u0408\0\u0433\0\u045e\0\53\0\u0489\0\53"+
    "\0\u03dd\0\u04b4\0\u04df\0\u0102\0\53\0\u050a\0\u0535\0\u0560"+
    "\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8"+
    "\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810"+
    "\0\u083b\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\53\0\53"+
    "\0\u04df\0\u093d\0\u0968\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f"+
    "\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97"+
    "\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef"+
    "\0\u0d1a\0\201\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c"+
    "\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74"+
    "\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc"+
    "\0\u10f7\0\u1122\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224"+
    "\0\u124f\0\u127a\0\u12a5\0\u12d0\0\u12fb\0\u1326\0\u1351\0\u137c"+
    "\0\u13a7\0\u13d2\0\u13fd\0\u1428\0\u1453\0\u147e\0\u14a9\0\u14d4"+
    "\0\u14ff\0\u11a3\0\u152a\0\u1555\0\u1580\0\u15ab\0\u15d6\0\u1601"+
    "\0\u162c\0\u1657\0\u1682\0\u16ad\0\u16d8\0\u1703\0\u172e\0\u1759"+
    "\0\u1784\0\u17af\0\u17da\0\u1805\0\u1830\0\u185b\0\u1886\0\u18b1"+
    "\0\u18dc\0\u1907\0\u1932";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\5\1\11\1\12\1\13\1\14\1\4\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\4\1\24\1\25"+
    "\2\4\1\26\1\27\4\4\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\40\54\0"+
    "\1\42\1\4\1\0\1\42\5\0\26\4\14\0\2\4"+
    "\1\0\1\4\5\0\26\4\16\0\1\5\4\0\1\5"+
    "\43\0\2\42\1\0\1\6\1\43\4\0\26\42\17\0"+
    "\1\44\46\0\6\10\1\45\1\46\1\47\42\10\10\11"+
    "\1\0\42\11\1\0\2\4\1\0\1\4\5\0\1\4"+
    "\1\50\4\4\1\51\17\4\14\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\52\2\4\1\53\10\4\1\54\7\4"+
    "\14\0\2\4\1\0\1\4\5\0\3\4\1\55\22\4"+
    "\14\0\2\4\1\0\1\4\5\0\1\4\1\56\24\4"+
    "\14\0\2\4\1\0\1\4\5\0\1\4\1\57\24\4"+
    "\14\0\2\4\1\0\1\4\5\0\2\4\1\60\23\4"+
    "\14\0\2\4\1\0\1\4\5\0\3\4\1\61\2\4"+
    "\1\62\17\4\14\0\2\4\1\0\1\4\5\0\6\4"+
    "\1\63\17\4\14\0\2\4\1\0\1\4\5\0\2\4"+
    "\1\64\5\4\1\65\15\4\14\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\66\24\4\14\0\2\4\1\0\1\4"+
    "\5\0\3\4\1\67\5\4\1\70\14\4\14\0\2\4"+
    "\1\0\1\4\5\0\10\4\1\71\1\72\14\4\14\0"+
    "\2\4\1\0\1\4\5\0\6\4\1\73\2\4\1\74"+
    "\14\4\14\0\2\4\1\0\1\4\5\0\1\4\1\75"+
    "\24\4\14\0\2\76\7\0\26\76\14\0\2\76\7\0"+
    "\26\76\1\0\1\77\12\0\2\76\7\0\26\76\4\0"+
    "\1\100\53\0\1\100\55\0\1\36\3\0\2\42\1\0"+
    "\1\42\5\0\26\42\17\0\1\101\46\0\6\10\1\47"+
    "\1\10\1\0\42\10\6\47\1\45\1\102\43\47\1\0"+
    "\2\4\1\0\1\4\5\0\2\4\1\103\23\4\14\0"+
    "\2\4\1\0\1\4\5\0\14\4\1\104\11\4\14\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\74\24\4\14\0"+
    "\2\4\1\0\1\4\5\0\15\4\1\105\10\4\14\0"+
    "\2\4\1\0\1\4\5\0\2\4\1\106\23\4\14\0"+
    "\1\107\1\4\1\0\1\4\5\0\26\4\14\0\2\4"+
    "\1\0\1\4\5\0\2\4\1\110\23\4\14\0\2\4"+
    "\1\0\1\4\5\0\6\4\1\111\17\4\14\0\2\4"+
    "\1\0\1\4\5\0\7\4\1\112\16\4\14\0\2\4"+
    "\1\0\1\4\5\0\17\4\1\113\6\4\14\0\2\4"+
    "\1\0\1\4\5\0\10\4\1\114\15\4\14\0\2\4"+
    "\1\0\1\4\5\0\16\4\1\115\7\4\14\0\2\4"+
    "\1\0\1\4\5\0\11\4\1\116\14\4\14\0\2\4"+
    "\1\0\1\4\5\0\22\4\1\117\3\4\14\0\2\4"+
    "\1\0\1\4\5\0\2\4\1\120\2\4\1\121\20\4"+
    "\14\0\2\4\1\0\1\4\5\0\5\4\1\122\4\4"+
    "\1\123\13\4\14\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\124\15\4\14\0\2\4\1\0\1\4\5\0\1\4"+
    "\1\125\24\4\14\0\2\4\1\0\1\4\5\0\7\4"+
    "\1\126\16\4\14\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\127\15\4\14\0\2\4\1\0\1\4\5\0\14\4"+
    "\1\130\11\4\14\0\2\4\1\0\1\4\5\0\22\4"+
    "\1\131\3\4\14\0\2\76\1\0\1\76\5\0\26\76"+
    "\13\0\10\47\1\0\42\47\1\0\2\4\1\0\1\4"+
    "\5\0\3\4\1\132\22\4\14\0\2\4\1\0\1\4"+
    "\5\0\14\4\1\133\11\4\14\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\134\15\4\14\0\2\4\1\0\1\4"+
    "\5\0\3\4\1\135\22\4\14\0\2\4\1\0\1\4"+
    "\5\0\7\4\1\136\16\4\14\0\1\137\1\4\1\0"+
    "\1\4\5\0\26\4\14\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\140\23\4\14\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\141\15\4\14\0\2\4\1\0\1\4\5\0"+
    "\6\4\1\142\17\4\14\0\2\4\1\0\1\4\5\0"+
    "\5\4\1\143\20\4\14\0\2\4\1\0\1\4\5\0"+
    "\12\4\1\144\13\4\14\0\2\4\1\0\1\4\5\0"+
    "\12\4\1\145\13\4\14\0\2\4\1\0\1\4\5\0"+
    "\3\4\1\146\22\4\14\0\2\4\1\0\1\4\5\0"+
    "\6\4\1\144\17\4\14\0\2\4\1\0\1\4\5\0"+
    "\15\4\1\147\10\4\14\0\2\4\1\0\1\4\5\0"+
    "\15\4\1\150\10\4\14\0\2\4\1\0\1\4\5\0"+
    "\23\4\1\151\2\4\14\0\2\4\1\0\1\4\5\0"+
    "\16\4\1\152\7\4\14\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\153\23\4\14\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\154\15\4\14\0\1\155\1\4\1\0\1\4"+
    "\5\0\1\4\1\156\24\4\14\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\103\24\4\14\0\2\4\1\0\1\4"+
    "\5\0\23\4\1\157\2\4\14\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\154\24\4\14\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\160\24\4\14\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\161\15\4\14\0\2\4\1\0\1\4"+
    "\5\0\6\4\1\62\17\4\14\0\2\4\1\0\1\4"+
    "\5\0\1\162\4\4\1\16\20\4\14\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\163\16\4\14\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\164\14\4\14\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\165\23\4\14\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\166\24\4\14\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\132\14\4\14\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\167\24\4\14\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\132\13\4\14\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\170\24\4\14\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\171\24\4\14\0\2\4\1\0"+
    "\1\4\5\0\5\4\1\172\20\4\14\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\173\14\4\14\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\174\11\4\14\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\175\22\4\14\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\176\17\4\14\0\2\4\1\0"+
    "\1\4\5\0\4\4\1\177\21\4\14\0\2\4\1\0"+
    "\1\4\5\0\24\4\1\161\1\4\14\0\2\4\1\0"+
    "\1\4\5\0\5\4\1\200\20\4\14\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\201\14\4\14\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\132\24\4\14\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\202\15\4\14\0\2\4\1\0"+
    "\1\4\5\0\21\4\1\144\4\4\14\0\2\4\1\0"+
    "\1\4\5\0\1\132\25\4\14\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\203\23\4\14\0\2\4\1\0\1\4"+
    "\5\0\1\204\25\4\14\0\2\4\1\0\1\4\5\0"+
    "\11\4\1\205\14\4\14\0\2\4\1\0\1\4\5\0"+
    "\12\4\1\161\13\4\14\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\144\23\4\14\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\206\15\4\14\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\207\24\4\14\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\132\23\4\14\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\210\15\4\14\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\211\24\4\14\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\201\24\4\14\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\132\15\4\14\0\2\4\1\0\1\4\5\0"+
    "\11\4\1\212\14\4\14\0\2\4\1\0\1\4\5\0"+
    "\11\4\1\213\14\4\14\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\214\24\4\14\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\215\15\4\14\0\1\216\1\4\1\0\1\4"+
    "\5\0\26\4\14\0\2\4\1\0\1\4\5\0\15\4"+
    "\1\217\10\4\14\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\220\15\4\14\0\2\4\1\0\1\4\5\0\14\4"+
    "\1\170\11\4\14\0\2\4\1\0\1\4\5\0\12\4"+
    "\1\221\13\4\14\0\2\4\1\0\1\4\5\0\1\222"+
    "\25\4\14\0\1\155\1\4\1\0\1\4\5\0\26\4"+
    "\14\0\2\4\1\0\1\4\5\0\11\4\1\223\14\4"+
    "\14\0\2\4\1\0\1\4\5\0\11\4\1\146\14\4"+
    "\14\0\2\4\1\0\1\4\5\0\3\4\1\224\22\4"+
    "\14\0\2\4\1\0\1\4\5\0\6\4\1\212\17\4"+
    "\14\0\1\225\1\4\1\0\1\4\5\0\26\4\14\0"+
    "\2\4\1\0\1\4\5\0\10\4\1\226\15\4\14\0"+
    "\2\4\1\0\1\4\5\0\10\4\1\221\15\4\14\0"+
    "\2\4\1\0\1\4\5\0\1\227\11\4\1\230\13\4"+
    "\14\0\2\4\1\0\1\4\5\0\14\4\1\231\11\4"+
    "\14\0\2\4\1\0\1\4\5\0\1\4\1\232\24\4"+
    "\14\0\2\4\1\0\1\4\5\0\6\4\1\233\17\4"+
    "\14\0\2\4\1\0\1\4\5\0\25\4\1\234\14\0"+
    "\2\4\1\0\1\4\5\0\2\4\1\235\23\4\14\0"+
    "\2\4\1\0\1\4\5\0\13\4\1\236\12\4\14\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\237\24\4\14\0"+
    "\2\4\1\0\1\4\5\0\7\4\1\240\16\4\14\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\241\24\4\14\0"+
    "\2\4\1\0\1\4\5\0\20\4\1\103\5\4\14\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\242\14\4\14\0"+
    "\2\4\1\0\1\4\5\0\14\4\1\103\11\4\14\0"+
    "\2\4\1\0\1\4\5\0\14\4\1\243\11\4\14\0"+
    "\2\4\1\0\1\4\5\0\7\4\1\236\16\4\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6493];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\33\1\1\11\1\1\1\11\4\1\1\11"+
    "\1\1\1\0\27\1\2\11\1\1\1\0\141\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private final TablaSimbolos tablaSimbolos = new TablaSimbolos();
    private final TablaFunciones tablaFunciones = new TablaFunciones();

    public TablaSimbolos getTablaSimbolos() {
        return this.tablaSimbolos;
    }

    public TablaFunciones getTablaFunciones() { 
        return this.tablaFunciones;
    }

    private Tokens token(String lex, String comp, int li, int c){
        return new Tokens(lex, comp, li+1, c+1); 
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return token(yytext(),"OPE_LOGICO",yyline,yycolumn);
          }
        case 17: break;
        case 9: 
          { return token(yytext(),"OPE_ASIGNACION",yyline,yycolumn);
          }
        case 18: break;
        case 12: 
          { return token(yytext(),"DELIMITADOR",yyline,yycolumn);
          }
        case 19: break;
        case 15: 
          { return token(yytext(),"PALABRA_RESERVADA",yyline,yycolumn);
          }
        case 20: break;
        case 13: 
          { return token(yytext(),"ERROR_NUMERO_MALFORMADO",yyline,yycolumn);
          }
        case 21: break;
        case 7: 
          { return token(yytext(),"ERROR_CADENA_NO_CERRADA",yyline,yycolumn);
          }
        case 22: break;
        case 1: 
          { return token(yytext(),"ERROR_CARACTER_INVALIDO",yyline,yycolumn);
          }
        case 23: break;
        case 14: 
          { return token(yytext(),"CADENA",yyline,yycolumn);
          }
        case 24: break;
        case 6: 
          { return token(yytext(), "ERROR", yyline, yycolumn);
          }
        case 25: break;
        case 3: 
          { // Revisa la "Tabla Fija"
        if (TablaPalabrasReservadas.esReservada(yytext())){
            return token(yytext(),"ERROR_IDENTIFICADOR_ES_PALABRA_RESERVADA",yyline,yycolumn);
        } else {
            // Si no es reservada, la registra en la "Tabla de identificadores"
            tablaSimbolos.registrarIdentificador(yytext(), yyline+1, yycolumn+1);
            return token(yytext(),"IDENTIFICADOR",yyline,yycolumn);
        }
          }
        case 26: break;
        case 2: 
          { return token(yytext(), "ERROR_IDENTIFICADOR_INVALIDO", yyline, yycolumn);
          }
        case 27: break;
        case 4: 
          { /* ignorar */
          }
        case 28: break;
        case 16: 
          { return token(yytext(), "ERROR_LEXICO", yyline, yycolumn);
          }
        case 29: break;
        case 5: 
          { return token(yytext(),"NUMERO",yyline,yycolumn);
          }
        case 30: break;
        case 8: 
          { return token(yytext(),"OPE_ARITMETICO",yyline,yycolumn);
          }
        case 31: break;
        case 11: 
          { return token(yytext(),"OPE_RELACIONAL",yyline,yycolumn);
          }
        case 32: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
