/* The following code was generated by JFlex 1.4.3 on 03/12/25, 21:39 */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 03/12/25, 21:39 from the specification file
 * <tt>C:/Users/alanc/OneDrive/Documents/Tec/11vo Semestre/Lenguajes y Automatas 1/Unidad 4/Proyecto Compilador/compilercode-compilador/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\10\2\0\1\3\22\0\1\3\1\45\1\6\1\11"+
    "\1\0\1\54\1\50\1\0\1\52\1\52\1\43\1\43\1\52\1\53"+
    "\1\5\1\53\12\4\1\52\1\52\1\46\1\44\1\47\2\0\17\2"+
    "\1\42\2\2\1\41\1\40\6\2\1\52\1\7\1\52\1\0\1\1"+
    "\1\0\1\23\1\34\1\26\1\33\1\20\1\16\1\30\1\37\1\13"+
    "\1\36\1\31\1\24\1\17\1\14\1\15\1\27\1\2\1\22\1\12"+
    "\1\21\1\35\1\32\1\2\1\25\2\2\1\52\1\51\1\52\103\0"+
    "\1\54\7\0\1\54\3\0\1\54\3\0\1\54\1\0\1\54\6\0"+
    "\1\54\1\0\1\54\4\0\1\54\7\0\1\54\3\0\1\54\3\0"+
    "\1\54\1\0\1\54\6\0\1\54\1\0\1\54\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\4\17\3\1\10\1\11\1\12\1\13\1\1\2\14"+
    "\2\6\1\2\2\15\1\16\1\7\1\0\1\17\33\3"+
    "\1\20\1\13\1\21\1\12\1\5\1\0\37\3\1\17"+
    "\46\3\1\17\2\3\1\17\43\3\1\17\143\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[282];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3"+
    "\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de\0\u040b"+
    "\0\u0438\0\u0465\0\u0492\0\u0492\0\u04bf\0\u04ec\0\55\0\u0438"+
    "\0\55\0\u0519\0\u0546\0\u010e\0\55\0\u0573\0\u05a0\0\u05cd"+
    "\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735"+
    "\0\u0762\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d"+
    "\0\u08ca\0\u08f7\0\u0924\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u0a05"+
    "\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9\0\55\0\55\0\55\0\u0546"+
    "\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21"+
    "\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89"+
    "\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4\0\u0ef1"+
    "\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u102c\0\u1059"+
    "\0\207\0\u1086\0\u10b3\0\u10e0\0\u110d\0\u113a\0\u1167\0\u1194"+
    "\0\u11c1\0\u11ee\0\u121b\0\u1248\0\u1275\0\u12a2\0\u12cf\0\u12fc"+
    "\0\u1329\0\u1356\0\u1383\0\u13b0\0\u13dd\0\u140a\0\u1437\0\u1464"+
    "\0\u1491\0\u14be\0\u14eb\0\u1518\0\u1545\0\u1572\0\u159f\0\u15cc"+
    "\0\u15f9\0\u1626\0\u1653\0\u1680\0\u16ad\0\u16da\0\u1707\0\u1734"+
    "\0\u1761\0\u178e\0\u17bb\0\u17e8\0\u1815\0\u1842\0\u186f\0\u189c"+
    "\0\u18c9\0\u18f6\0\u1923\0\u1950\0\u197d\0\u19aa\0\u19d7\0\u1a04"+
    "\0\u1a31\0\u1a5e\0\u1a8b\0\u1ab8\0\u1ae5\0\u1b12\0\u1b3f\0\u1b6c"+
    "\0\u1b99\0\u1bc6\0\u1bf3\0\u1c20\0\u1c4d\0\u1c7a\0\u1ca7\0\u1cd4"+
    "\0\u1d01\0\u1d2e\0\u1d5b\0\u1734\0\u1d88\0\u1db5\0\u1de2\0\u1e0f"+
    "\0\u1e3c\0\u1e69\0\u1e96\0\u1ec3\0\u1ef0\0\u1f1d\0\u1f4a\0\u1f77"+
    "\0\u1fa4\0\u1fd1\0\u1ffe\0\u202b\0\u2058\0\u2085\0\u20b2\0\u20df"+
    "\0\u210c\0\u2139\0\u2166\0\u2193\0\u21c0\0\u21ed\0\u221a\0\u2247"+
    "\0\u2274\0\u22a1\0\u22ce\0\u22fb\0\u2328\0\u2355\0\u2382\0\u23af"+
    "\0\u23dc\0\u2409\0\u2436\0\u2463\0\u2490\0\u24bd\0\u24ea\0\u2517"+
    "\0\u2544\0\u2571\0\u259e\0\u25cb\0\u25f8\0\u2625\0\u2652\0\u267f"+
    "\0\u26ac\0\u26d9\0\u2706\0\u2733\0\u2760\0\u278d\0\u27ba\0\u27e7"+
    "\0\u2814\0\u2841\0\u286e\0\u289b\0\u28c8\0\u28f5\0\u2922\0\u294f"+
    "\0\u297c\0\u29a9\0\u29d6\0\u2a03\0\u2a30\0\u2a5d\0\u2a8a\0\u2ab7"+
    "\0\u2ae4\0\u2b11\0\u2b3e\0\u2b6b\0\u2b98\0\u2bc5\0\u2bf2\0\u2c1f"+
    "\0\u2c4c\0\u2c79\0\u2ca6\0\u2cd3\0\u2d00\0\u2d2d\0\u2d5a\0\u2d87"+
    "\0\u2db4\0\u2de1\0\u2e0e\0\u2e3b\0\u2e68\0\u2e95\0\u2ec2\0\u2eef"+
    "\0\u2f1c\0\u2f49";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[282];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\5\1\11\1\12\1\13\1\14\1\4\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\4\1\24\1\25"+
    "\1\26\1\4\1\27\1\30\7\4\1\31\1\32\1\33"+
    "\2\34\1\35\1\36\1\37\1\40\1\41\56\0\1\42"+
    "\1\4\1\0\1\42\5\0\31\4\13\0\2\4\1\0"+
    "\1\4\5\0\31\4\15\0\1\5\4\0\1\5\45\0"+
    "\2\42\1\0\1\6\1\43\4\0\31\42\16\0\1\44"+
    "\50\0\6\10\1\45\1\46\1\47\44\10\10\11\1\0"+
    "\44\11\1\0\2\4\1\0\1\4\5\0\1\4\1\50"+
    "\4\4\1\51\22\4\13\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\52\2\4\1\53\10\4\1\54\12\4\13\0"+
    "\2\4\1\0\1\4\5\0\3\4\1\55\25\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\56\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\57\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\60\1\4\1\61\21\4"+
    "\1\62\4\4\13\0\2\4\1\0\1\4\5\0\3\4"+
    "\1\63\2\4\1\64\1\4\1\65\1\66\17\4\13\0"+
    "\2\4\1\0\1\4\5\0\6\4\1\67\22\4\13\0"+
    "\2\4\1\0\1\4\5\0\2\4\1\70\5\4\1\71"+
    "\20\4\13\0\2\4\1\0\1\4\5\0\1\4\1\72"+
    "\27\4\13\0\2\4\1\0\1\4\5\0\3\4\1\73"+
    "\5\4\1\74\17\4\13\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\75\1\76\17\4\13\0\2\4\1\0\1\4"+
    "\5\0\6\4\1\77\22\4\13\0\2\4\1\0\1\4"+
    "\5\0\6\4\1\100\2\4\1\101\17\4\13\0\2\4"+
    "\1\0\1\4\5\0\1\4\1\102\4\4\1\103\22\4"+
    "\13\0\2\104\7\0\31\104\13\0\2\104\7\0\31\104"+
    "\1\0\1\105\2\0\1\106\6\0\2\104\7\0\31\104"+
    "\1\0\1\105\11\0\2\104\7\0\31\104\5\0\1\107"+
    "\55\0\1\107\4\0\2\42\1\0\1\42\5\0\31\42"+
    "\16\0\1\110\50\0\6\10\1\47\1\10\1\0\44\10"+
    "\6\47\1\45\1\111\45\47\1\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\112\26\4\13\0\2\4\1\0\1\4"+
    "\5\0\14\4\1\113\14\4\13\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\101\27\4\13\0\2\4\1\0\1\4"+
    "\5\0\15\4\1\114\13\4\13\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\115\26\4\13\0\1\116\1\4\1\0"+
    "\1\4\5\0\31\4\13\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\117\26\4\13\0\2\4\1\0\1\4\5\0"+
    "\6\4\1\120\22\4\13\0\2\4\1\0\1\4\5\0"+
    "\7\4\1\121\21\4\13\0\2\4\1\0\1\4\5\0"+
    "\7\4\1\122\21\4\13\0\2\4\1\0\1\4\5\0"+
    "\6\4\1\123\22\4\13\0\2\4\1\0\1\4\5\0"+
    "\17\4\1\124\11\4\13\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\125\20\4\13\0\2\4\1\0\1\4\5\0"+
    "\11\4\1\126\17\4\13\0\2\4\1\0\1\4\5\0"+
    "\22\4\1\127\6\4\13\0\2\4\1\0\1\4\5\0"+
    "\16\4\1\130\12\4\13\0\2\4\1\0\1\4\5\0"+
    "\11\4\1\131\17\4\13\0\2\4\1\0\1\4\5\0"+
    "\22\4\1\132\6\4\13\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\133\2\4\1\134\23\4\13\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\135\2\4\1\136\4\4\1\137"+
    "\16\4\13\0\2\4\1\0\1\4\5\0\5\4\1\140"+
    "\2\4\1\141\20\4\13\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\142\27\4\13\0\2\4\1\0\1\4\5\0"+
    "\7\4\1\143\21\4\13\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\144\26\4\13\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\145\20\4\13\0\2\4\1\0\1\4\5\0"+
    "\14\4\1\146\14\4\13\0\2\4\1\0\1\4\5\0"+
    "\22\4\1\147\6\4\13\0\2\4\1\0\1\4\5\0"+
    "\4\4\1\150\24\4\13\0\2\104\1\0\1\104\5\0"+
    "\31\104\12\0\10\47\1\0\44\47\1\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\151\25\4\13\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\152\14\4\13\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\153\20\4\13\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\154\25\4\13\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\155\21\4\13\0\1\156\1\4"+
    "\1\0\1\4\5\0\31\4\13\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\157\26\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\160\1\161\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\162\20\4\13\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\163\14\4\13\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\164\22\4\13\0\2\4\1\0"+
    "\1\4\5\0\5\4\1\165\23\4\13\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\166\26\4\13\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\167\16\4\13\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\170\16\4\13\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\171\16\4\13\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\172\25\4\13\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\170\22\4\13\0\2\4\1\0"+
    "\1\4\5\0\15\4\1\173\13\4\13\0\2\4\1\0"+
    "\1\4\5\0\1\174\23\4\1\175\4\4\13\0\2\4"+
    "\1\0\1\4\5\0\15\4\1\176\13\4\13\0\2\4"+
    "\1\0\1\4\5\0\23\4\1\177\5\4\13\0\2\4"+
    "\1\0\1\4\5\0\15\4\1\112\13\4\13\0\2\4"+
    "\1\0\1\4\5\0\16\4\1\200\12\4\13\0\2\4"+
    "\1\0\1\4\5\0\2\4\1\201\26\4\13\0\2\4"+
    "\1\0\1\4\5\0\10\4\1\202\20\4\13\0\2\4"+
    "\1\0\1\4\5\0\6\4\1\203\22\4\13\0\1\204"+
    "\1\4\1\0\1\4\5\0\1\4\1\205\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\112\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\23\4\1\206\5\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\207\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\202\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\210\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\10\4\1\211\20\4\13\0"+
    "\2\4\1\0\1\4\5\0\6\4\1\64\22\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\212\4\4\1\16\23\4"+
    "\13\0\2\4\1\0\1\4\5\0\7\4\1\213\21\4"+
    "\13\0\2\4\1\0\1\4\5\0\23\4\1\214\5\4"+
    "\13\0\2\4\1\0\1\4\5\0\21\4\1\215\7\4"+
    "\13\0\2\4\1\0\1\4\5\0\11\4\1\216\17\4"+
    "\13\0\2\4\1\0\1\4\5\0\23\4\1\217\5\4"+
    "\13\0\2\4\1\0\1\4\5\0\2\4\1\220\26\4"+
    "\13\0\2\4\1\0\1\4\5\0\1\4\1\221\27\4"+
    "\13\0\2\4\1\0\1\4\5\0\1\222\30\4\13\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\223\17\4\13\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\151\17\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\224\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\12\4\1\151\16\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\225\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\7\4\1\226\21\4\13\0"+
    "\2\4\1\0\1\4\5\0\23\4\1\227\5\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\230\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\5\4\1\231\23\4\13\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\232\17\4\13\0"+
    "\2\4\1\0\1\4\5\0\14\4\1\233\14\4\13\0"+
    "\2\4\1\0\1\4\5\0\3\4\1\234\25\4\13\0"+
    "\2\4\1\0\1\4\5\0\10\4\1\235\20\4\13\0"+
    "\2\4\1\0\1\4\5\0\6\4\1\236\22\4\13\0"+
    "\2\4\1\0\1\4\5\0\4\4\1\237\24\4\13\0"+
    "\2\4\1\0\1\4\5\0\24\4\1\211\4\4\13\0"+
    "\2\4\1\0\1\4\5\0\2\4\1\240\26\4\13\0"+
    "\2\4\1\0\1\4\5\0\5\4\1\241\23\4\13\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\242\17\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\151\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\10\4\1\243\20\4\13\0"+
    "\2\4\1\0\1\4\5\0\14\4\1\244\14\4\13\0"+
    "\2\4\1\0\1\4\5\0\3\4\1\245\25\4\13\0"+
    "\2\4\1\0\1\4\5\0\21\4\1\170\7\4\13\0"+
    "\2\4\1\0\1\4\5\0\7\4\1\246\21\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\151\30\4\13\0\2\4"+
    "\1\0\1\4\5\0\2\4\1\247\26\4\13\0\2\4"+
    "\1\0\1\4\5\0\1\4\1\250\27\4\13\0\1\251"+
    "\1\4\1\0\1\4\5\0\31\4\13\0\2\4\1\0"+
    "\1\4\5\0\1\252\30\4\13\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\253\17\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\254\20\4\13\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\255\26\4\13\0\2\4\1\0\1\4"+
    "\5\0\12\4\1\211\16\4\13\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\170\26\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\256\20\4\13\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\257\27\4\13\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\151\26\4\13\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\260\17\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\261\20\4\13\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\262\27\4\13\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\263\27\4\13\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\242\27\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\151\20\4\13\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\264\17\4\13\0\2\4\1\0\1\4"+
    "\5\0\7\4\1\265\21\4\13\0\1\266\1\4\1\0"+
    "\1\4\5\0\1\267\30\4\13\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\270\17\4\13\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\271\17\4\13\0\2\4\1\0\1\4"+
    "\5\0\14\4\1\272\14\4\13\0\2\4\1\0\1\4"+
    "\5\0\1\273\30\4\13\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\274\27\4\13\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\275\20\4\13\0\2\4\1\0\1\4\5\0"+
    "\23\4\1\276\5\4\13\0\2\4\1\0\1\4\5\0"+
    "\7\4\1\112\21\4\13\0\1\277\1\4\1\0\1\4"+
    "\5\0\31\4\13\0\2\4\1\0\1\4\5\0\15\4"+
    "\1\300\13\4\13\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\301\20\4\13\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\302\20\4\13\0\2\4\1\0\1\4\5\0\14\4"+
    "\1\225\14\4\13\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\303\20\4\13\0\2\4\1\0\1\4\5\0\23\4"+
    "\1\304\5\4\13\0\2\4\1\0\1\4\5\0\1\4"+
    "\1\305\27\4\13\0\1\306\1\4\1\0\1\4\5\0"+
    "\31\4\13\0\2\4\1\0\1\4\5\0\10\4\1\307"+
    "\20\4\13\0\2\4\1\0\1\4\5\0\12\4\1\310"+
    "\16\4\13\0\2\4\1\0\1\4\5\0\1\4\1\311"+
    "\27\4\13\0\2\4\1\0\1\4\5\0\1\4\1\312"+
    "\27\4\13\0\2\4\1\0\1\4\5\0\1\313\30\4"+
    "\13\0\1\204\1\4\1\0\1\4\5\0\31\4\13\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\314\27\4\13\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\315\17\4\13\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\172\17\4\13\0"+
    "\1\316\1\4\1\0\1\4\5\0\31\4\13\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\317\25\4\13\0\1\320"+
    "\1\4\1\0\1\4\5\0\31\4\13\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\321\20\4\13\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\322\26\4\13\0\2\4\1\0"+
    "\1\4\5\0\4\4\1\165\24\4\13\0\1\323\1\4"+
    "\1\0\1\4\5\0\30\4\1\324\13\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\264\22\4\13\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\325\25\4\13\0\2\4\1\0"+
    "\1\4\5\0\5\4\1\326\23\4\13\0\1\327\1\4"+
    "\1\0\1\4\5\0\31\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\330\20\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\331\20\4\13\0\2\4\1\0\1\4"+
    "\5\0\26\4\1\332\2\4\13\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\310\20\4\13\0\2\4\1\0\1\4"+
    "\5\0\7\4\1\333\1\4\1\334\17\4\13\0\2\4"+
    "\1\0\1\4\5\0\11\4\1\330\17\4\13\0\2\4"+
    "\1\0\1\4\5\0\1\4\1\335\27\4\13\0\2\4"+
    "\1\0\1\4\5\0\11\4\1\336\17\4\13\0\2\4"+
    "\1\0\1\4\5\0\10\4\1\337\20\4\13\0\2\4"+
    "\1\0\1\4\5\0\2\4\1\340\26\4\13\0\2\4"+
    "\1\0\1\4\5\0\22\4\1\341\6\4\13\0\2\4"+
    "\1\0\1\4\5\0\1\342\11\4\1\343\16\4\13\0"+
    "\1\344\1\4\1\0\1\4\5\0\31\4\13\0\2\4"+
    "\1\0\1\4\5\0\14\4\1\345\14\4\13\0\2\4"+
    "\1\0\1\4\5\0\11\4\1\346\17\4\13\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\347\25\4\13\0\2\4"+
    "\1\0\1\4\5\0\12\4\1\350\16\4\13\0\2\4"+
    "\1\0\1\4\5\0\14\4\1\351\14\4\13\0\2\4"+
    "\1\0\1\4\5\0\23\4\1\352\5\4\13\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\353\25\4\13\0\2\4"+
    "\1\0\1\4\5\0\6\4\1\354\22\4\13\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\355\25\4\13\0\2\4"+
    "\1\0\1\4\5\0\1\4\1\356\27\4\13\0\2\4"+
    "\1\0\1\4\5\0\6\4\1\357\22\4\13\0\2\4"+
    "\1\0\1\4\5\0\7\4\1\360\21\4\13\0\2\4"+
    "\1\0\1\4\5\0\25\4\1\361\3\4\13\0\2\4"+
    "\1\0\1\4\5\0\22\4\1\362\6\4\13\0\2\4"+
    "\1\0\1\4\5\0\17\4\1\363\11\4\13\0\2\4"+
    "\1\0\1\4\5\0\4\4\1\364\24\4\13\0\2\4"+
    "\1\0\1\4\5\0\1\4\1\300\27\4\13\0\2\4"+
    "\1\0\1\4\5\0\7\4\1\365\21\4\13\0\2\4"+
    "\1\0\1\4\5\0\16\4\1\151\12\4\13\0\2\4"+
    "\1\0\1\4\5\0\1\366\30\4\13\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\367\16\4\13\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\370\26\4\13\0\2\4\1\0"+
    "\1\4\5\0\13\4\1\371\15\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\372\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\373\27\4\13\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\374\16\4\13\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\375\22\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\376\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\377\25\4\13\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\u0100\25\4\13\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\264\25\4\13\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\u0101\21\4\13\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\u0102\27\4\13\0\2\4\1\0"+
    "\1\4\5\0\22\4\1\130\6\4\13\0\2\4\1\0"+
    "\1\4\5\0\20\4\1\112\10\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\u0103\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\u0104\26\4\13\0\2\4\1\0"+
    "\1\4\5\0\22\4\1\u0105\6\4\13\0\2\4\1\0"+
    "\1\4\5\0\5\4\1\u0106\23\4\13\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\u0107\21\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\u0108\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\112\14\4\13\0\2\4\1\0"+
    "\1\4\5\0\27\4\1\273\1\4\13\0\2\4\1\0"+
    "\1\4\5\0\15\4\1\u0109\13\4\13\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\255\22\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\u010a\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\112\20\4\13\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\u010b\14\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\u010c\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\170\21\4\13\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\371\21\4\13\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\u010d\16\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\u010e\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\22\4\1\u010f\6\4\13\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\u0110\20\4\13\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\u0111\17\4\13\0\2\4\1\0"+
    "\1\4\5\0\1\u0112\30\4\13\0\1\u0113\1\4\1\0"+
    "\1\4\5\0\31\4\13\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\u0114\20\4\13\0\2\4\1\0\1\4\5\0"+
    "\6\4\1\u0115\22\4\13\0\2\4\1\0\1\4\5\0"+
    "\1\u0116\30\4\13\0\2\4\1\0\1\4\5\0\6\4"+
    "\1\u0117\22\4\13\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\u0118\20\4\13\0\2\4\1\0\1\4\5\0\20\4"+
    "\1\u0119\10\4\13\0\2\4\1\0\1\4\5\0\11\4"+
    "\1\u011a\17\4\13\0\2\4\1\0\1\4\5\0\21\4"+
    "\1\243\7\4\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12150];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\34\1\1\11\1\1\1\11\3\1\1\11"+
    "\1\1\1\0\35\1\3\11\1\1\1\0\321\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[282];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private final TablaSimbolos tablaSimbolos = new TablaSimbolos();
    private final TablaFunciones tablaFunciones = new TablaFunciones();

    public TablaSimbolos getTablaSimbolos() {
        return this.tablaSimbolos;
    }

    public TablaFunciones getTablaFunciones() { 
        return this.tablaFunciones;
    }

    private Tokens token(String lex, String comp, int li, int c){
        return new Tokens(lex, comp, li+1, c+1); 
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return token(yytext(),"OPE_LOGICO",yyline,yycolumn);
          }
        case 18: break;
        case 9: 
          { return token(yytext(),"OPE_ASIGNACION",yyline,yycolumn);
          }
        case 19: break;
        case 17: 
          { return token(yytext(),"OPE_TRANSICION",yyline,yycolumn);
          }
        case 20: break;
        case 12: 
          { return token(yytext(),"DELIMITADOR",yyline,yycolumn);
          }
        case 21: break;
        case 15: 
          { return token(yytext(),"PALABRA_RESERVADA",yyline,yycolumn);
          }
        case 22: break;
        case 13: 
          { return token(yytext(),"ERROR_NUMERO_MALFORMADO",yyline,yycolumn);
          }
        case 23: break;
        case 7: 
          { return token(yytext(),"ERROR_CADENA_NO_CERRADA",yyline,yycolumn);
          }
        case 24: break;
        case 1: 
          { return token(yytext(),"ERROR_CARACTER_INVALIDO",yyline,yycolumn);
          }
        case 25: break;
        case 14: 
          { return token(yytext(),"CADENA",yyline,yycolumn);
          }
        case 26: break;
        case 6: 
          { return token(yytext(), "ERROR", yyline, yycolumn);
          }
        case 27: break;
        case 3: 
          { // Revisa la "Tabla Fija"
        if (TablaPalabrasReservadas.esReservada(yytext())){
            return token(yytext(),"ERROR_IDENTIFICADOR_ES_PALABRA_RESERVADA",yyline,yycolumn);
        } else {
            // Si no es reservada, la registra en la "Tabla de identificadores"
            tablaSimbolos.registrarIdentificador(yytext(), yyline+1, yycolumn+1);
            return token(yytext(),"IDENTIFICADOR",yyline,yycolumn);
        }
          }
        case 28: break;
        case 2: 
          { return token(yytext(), "ERROR_IDENTIFICADOR_INVALIDO", yyline, yycolumn);
          }
        case 29: break;
        case 4: 
          { /* ignorar */
          }
        case 30: break;
        case 16: 
          { return token(yytext(), "ERROR_LEXICO", yyline, yycolumn);
          }
        case 31: break;
        case 5: 
          { return token(yytext(),"NUMERO",yyline,yycolumn);
          }
        case 32: break;
        case 8: 
          { return token(yytext(),"OPE_ARITMETICO",yyline,yycolumn);
          }
        case 33: break;
        case 11: 
          { return token(yytext(),"OPE_RELACIONAL",yyline,yycolumn);
          }
        case 34: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
